services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc-server
    environment:
      EULA: "TRUE"
      MEMORY: "1G"
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-data:/data
    restart: unless-stopped

  romm:
    image: rommapp/romm:latest
    container_name: romm
    environment:
      ROMM_DB_TYPE: sqlite
    ports:
      - "5000:5000"
    volumes:
      - ./romm-data:/romm
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    ports:
      - "8080:80"
    volumes:
      - ./dashboard-config:/config
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    volumes:
      - ./music-data:/music
      - ./navidrome-data:/data
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - "8081:80"
    volumes:
      - ./files:/srv
      - ./filebrowser/filebrowser.db:/database.db
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
    restart: unless-stopped
